### ISSUE TITLE
GAZEBO frame rate is too slow in simulations

### ISSUE THREAD

**Issue by Ep3896** [Ep3896/pyicub-training#1]
In the code it voluntarily omitted the NVIDIA enviromental variables because it would not work for who has not an NVIDIA GPU.

For whoever has an NVIDIA GPU , is it better to copy and paste the following compose file that is linked.

The compose file adds the following environmental variables ( so the nvidia gpu is visible and can be used also for video): 

```
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "all"
 ``` 

and then the following snippet, just at the end of the service that you want to run using the GPU:

```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
``` 

This is the compose.yaml file (to copy and paste):

```yaml

x-common-env: &common-environment
  DISPLAY: ${DISPLAY:?err}
  PULSE_SERVER: unix:${XDG_RUNTIME_DIR:?err}/pulse/native
  PULSE_COOKIE: /run/pulse/cookie
  XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR:?err}
  XDG_DATA_DIRS: ${XDG_DATA_DIRS:?err}
  QT_X11_NO_MITSHM: "1"
  NO_AT_BRIDGE: "1"
  LIBGL_ALWAYS_SOFTWARE: "false"
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "all"


x-common-runtime: &common-runtime
  privileged: true
  stdin_open: true
  tty: true
  network_mode: host
  env_file:
    - .env

# Fully flattened volumes for pyicub
x-pyicub-volumes: &pyicub-volumes
  - /tmp/.X11-unix:/tmp/.X11-unix
  - ${HOME}/.config/pulse/cookie:/run/pulse/cookie
  - ${XDG_RUNTIME_DIR:?err}/pulse:${XDG_RUNTIME_DIR:?err}/pulse
  - ${XDG_RUNTIME_DIR:?err}/dconf:${XDG_RUNTIME_DIR:?err}/dconf
  - type: volume
    source: pyicub-workspace
    target: /workspace



# Common bind-mounts only (for test container)
x-common-volumes: &common-volumes
  - /tmp/.X11-unix:/tmp/.X11-unixs
  - ${HOME}/.config/pulse/cookie:/run/pulse/cookie
  - ${XDG_RUNTIME_DIR:?err}/pulse:${XDG_RUNTIME_DIR:?err}/pulse
  - ${XDG_RUNTIME_DIR:?err}/dconf:${XDG_RUNTIME_DIR:?err}/dconf



services:

  pyicub:
    <<: *common-runtime
    container_name: pyicub
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DOCKER_SRC: ${ROBOTOLOGY_IMAGE_NAME}
    image: ${PYICUB_IMAGE_NAME}
    command: ["/bin/bash", "-c", "terminator & bash /opt/scripts/runSetup.sh"]
    environment: *common-environment
    volumes: *pyicub-volumes
    profiles: ["backend"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  pyicub-frontend:
    container_name: pyicub-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${PYICUB_FRONTEND_IMAGE_NAME}
    network_mode: host
    depends_on:
      - pyicub
    volumes: 
      - type: volume
        source: pyicub-frontend-workspace
        target: /workspace/pyicub-frontend
    profiles: ["frontend"]

  pyicub-test:
    <<: *common-runtime
    image: ${PYICUB_IMAGE_NAME}
    command: ["bash", "/opt/scripts/runTests.sh"]
    environment: *common-environment
    volumes: *common-volumes
    profiles: ["test"]

volumes:
  pyicub-workspace:
  pyicub-frontend-workspace:  

```
